-- Creatre user conform documention snowflake
CREATE OR REPLACE USER 'USER_NAME'
    LOGIN_NAME = 'LOGIN_NAME'
    DISPLAY_NAME = 'DISPLAY_NAME'
    DISABLED = FALSE
    TYPE = 'PERSON/SERVICE'
    DEFAULT_WAREHOUSE = 'DEFAULT_WAREHOUSE'
    DEFAULT_NAMESPACE = 'DEFAULT_NAMESPACE'
    DEFAULT_ROLE = 'DEFAULT_ROLE'
    COMMENT = 'commenting on something for the user';


SHOW USERS LIKE 'USER_NAME';
DESC USER 'USER_NAME';
