-- CRETE TOKEN TO USER USE BY 365 DAYS

-- Create policy of authentication to max 365 day
CREATE AUTHENTICATION POLICY AUTHENTICATION_POLICY_PAT_MAX_DAY
  PAT_POLICY=(
    MAX_EXPIRY_IN_DAYS=365
  );

-- Check Policy
SHOW AUTHENTICATION POLICIES;
DESCRIBE AUTHENTICATION POLICY AUTHENTICATION_POLICY_PAT_MAX_DAY;

-- Aplly Policy the one user
ALTER USER 'USER' SET AUTHENTICATION POLICY AUTHENTICATION_POLICY_PAT_MAX_DAY;

-- Remove Policy Pat User
ALTER USER IF EXISTS 'USER' UNSET AUTHENTICATION POLICY;

-------------------------- CREATE TOKEN TO USER --------------------------
-- Create token to user
ALTER USER IF EXISTS 'USER_NAME'
  ADD PROGRAMMATIC ACCESS TOKEN 'TOKEN_USER_NAME' -- Name of token
    DAYS_TO_EXPIRY = 365
    ROLE_RESTRICTION = 'READER_ENV_DEV';

-- Check Token
SHOW USER PROGRAMMATIC ACCESS TOKENS FOR USER 'USER_NAME';

-- Create New Token to user
ALTER USER IF EXISTS 'USER_NAME' ROTATE PROGRAMMATIC ACCESS TOKEN 'TOKEN_USER_NAME';

-- Remove Token to user
ALTER USER IF EXISTS 'USER_NAME' REMOVE PROGRAMMATIC ACCESS TOKEN 'TOKEN_USER_NAME';
